
name: CI/CD workflow for Maven Build and SonarQube Scan

on:
  push:
    branches:
      - main     # your branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Build project with Maven
      - name: Build with Maven
        run: mvn clean install -f pom.xml

      # 4️⃣ SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectName=Online_Book_Store
            -Dsonar.projectKey=Online_Book_Store
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}       # sqa_cca8bd22925610da22c76d682b5aba12c4038ff0
          SONAR_HOST_URL: http://localhost:9000
