name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-sonar:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Start SonarQube
        shell: cmd
        run: |
          docker pull sonarqube:community
          docker run -d --name sonarqube -p 9000:9000 sonarqube:community
          timeout /t 60

      - name: Build and Sonar Scan
        shell: cmd
        run: |
          mvn clean verify sonar:sonar ^
            -Dsonar.projectKey=Online_Book_Store ^
            -Dsonar.projectName=Online_Book_Store ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.login=admin ^
            -Dsonar.password=admin

      - name: Cleanup
        if: always()
        shell: cmd
        run: |
          docker stop sonarqube
          docker rm sonarqube
