name: SonarQube Test
on: [push]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Start SonarQube (No Authentication)
      run: |
        docker run -d --name sonarqube -p 9000:9000 \
          -e SONAR_FORCEAUTHENTICATION=false \
          sonarqube:community
        sleep 90

    - name: Setup Java and Run Sonar
      run: |
        # Set Java environment
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        
        # Run Maven sonar without authentication
        mvn clean compile sonar:sonar \
          -Dsonar.projectKey=Online_Book_Store \
          -Dsonar.projectName="Online Book Store" \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.forceAuthentication=false
          
    - name: Cleanup
      run: docker rm -f sonarqube
