name: SonarQube Test
on: [push]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Start SonarQube (No Authentication)
      run: |
        docker run -d --name sonarqube -p 9000:9000 \
          -e SONAR_FORCEAUTHENTICATION=false \
          sonarqube:community
        sleep 90

    - name: Run SonarQube Analysis
      run: |
        mvn clean compile sonar:sonar \
          -Dsonar.projectKey=Online_Book_Store \
          -Dsonar.projectName="Online Book Store" \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.forceAuthentication=false
          
    - name: Cleanup
      if: always()
      run: docker rm -f sonarqube
