name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-sonar:
    runs-on: self-hosted   # Windows self-hosted runner
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Set up JDK 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # 4️⃣ Build project with Maven
      - name: Build with Maven
        shell: powershell
        run: mvn clean verify -B

      # 5️⃣ SonarQube Scan (Windows-compatible)
      - name: SonarQube Scan
        shell: powershell
        run: |
          # Environment variables
          $env:SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
          $env:SONAR_HOST_URL="http://localhost:9000"

          # Run Sonar scanner via Maven
          mvn sonar:sonar `
            -Dsonar.projectKey=Online_Book_Store `
            -Dsonar.projectName=Online_Book_Store `
            -Dsonar.host.url=$env:SONAR_HOST_URL `
            -Dsonar.login=$env:SONAR_TOKEN
